// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGtNfbBY4X_PKduIxvCYQvTyh2SplCIsU',
    appId: '1:866784349608:web:473cdfd0d9f69d497fe19d',
    messagingSenderId: '866784349608',
    projectId: 'stride-sisterhood',
    authDomain: 'stride-sisterhood.firebaseapp.com',
    storageBucket: 'stride-sisterhood.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFR5lG5XCxaoqEy4qjx-o2YcI0AEfL7LM',
    appId: '1:866784349608:android:738731c70db9e08f7fe19d',
    messagingSenderId: '866784349608',
    projectId: 'stride-sisterhood',
    storageBucket: 'stride-sisterhood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ94_upb7-CbrIXOp21Vls0Dj4TzkQzpk',
    appId: '1:866784349608:ios:1ebcc9090bb83bdf7fe19d',
    messagingSenderId: '866784349608',
    projectId: 'stride-sisterhood',
    storageBucket: 'stride-sisterhood.firebasestorage.app',
    iosBundleId: 'com.example.strideSisterhood1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ94_upb7-CbrIXOp21Vls0Dj4TzkQzpk',
    appId: '1:866784349608:ios:1ebcc9090bb83bdf7fe19d',
    messagingSenderId: '866784349608',
    projectId: 'stride-sisterhood',
    storageBucket: 'stride-sisterhood.firebasestorage.app',
    iosBundleId: 'com.example.strideSisterhood1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGtNfbBY4X_PKduIxvCYQvTyh2SplCIsU',
    appId: '1:866784349608:web:000674583b408c017fe19d',
    messagingSenderId: '866784349608',
    projectId: 'stride-sisterhood',
    authDomain: 'stride-sisterhood.firebaseapp.com',
    storageBucket: 'stride-sisterhood.firebasestorage.app',
  );
}
